import { createServer } from 'node:http'
import { readFile } from 'node:fs/promises'
import { existsSync, mkdirSync } from 'node:fs'
import { extname, join, normalize } from 'node:path'
import { chromium } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

const types = { '.html': 'text/html; charset=utf-8', '.js': 'application/javascript', '.css': 'text/css', '.webp': 'image/webp', '.svg': 'image/svg+xml', '.woff2': 'font/woff2' }
const server = createServer(async (request, response) => {
  try {
    const url = new URL(request.url, 'http://localhost')
    const clean = normalize(decodeURIComponent(url.pathname)).replace(/^(\.\.(\/|\\|$))+/, '')
    let file = join(process.cwd(), 'dist', clean === '/' ? 'index.html' : clean)
    if (!existsSync(file)) file = join(process.cwd(), 'dist', 'index.html')
    const content = await readFile(file)
    response.writeHead(200, { 'Content-Type': types[extname(file)] || 'application/octet-stream' })
    response.end(content)
  } catch {
    response.writeHead(500)
    response.end('Erreur')
  }
})
await new Promise((resolve) => server.listen(4179, '127.0.0.1', resolve))
mkdirSync('artifacts', { recursive: true })
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] })
const errors = []
const results = []
function assert(condition, message) { if (!condition) throw new Error(message); results.push(message) }
try {
  const desktopContext = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1, permissions: ['clipboard-read', 'clipboard-write'] })
  const desktop = await desktopContext.newPage()
  desktop.on('pageerror', (error) => errors.push(error.message))
  await desktop.goto('http://127.0.0.1:4179/', { waitUntil: 'networkidle' })
  await desktop.locator('.hero-image img').evaluate((image) => image.decode())
  await desktop.waitForTimeout(2000)
  console.log('HERO', await desktop.locator('.hero-image img').evaluate((image) => ({ loaded: image.complete, width: image.naturalWidth, height: image.clientHeight, rect: image.getBoundingClientRect().toJSON(), source: image.currentSrc, opacity: getComputedStyle(image).opacity })))
  await desktop.screenshot({ path: 'artifacts/desktop-hero.png' })
  assert(await desktop.locator('html').getAttribute('lang') === 'fr', 'Langue française')
  assert(await desktop.locator('h1').count() === 1, 'Un seul titre principal')
  assert(await desktop.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Aucun débordement à 1440 px')
  await desktop.locator('#univers').scrollIntoViewIfNeeded()
  await desktop.waitForTimeout(1000)
  await desktop.screenshot({ path: 'artifacts/desktop-universes.png' })
  const dimensions = await desktop.locator('.universe-card').evaluateAll((elements) => elements.map((element) => ({ width: element.getBoundingClientRect().width, height: element.getBoundingClientRect().height })))
  assert(dimensions.every((dimension) => Math.abs(dimension.width - dimensions[0].width) < 1 && dimension.height === dimensions[0].height), 'Triptyque strictement égal')
  const chapterHeights = await desktop.locator('.chapter').evaluateAll((elements) => elements.map((element) => element.getBoundingClientRect().height))
  assert(chapterHeights.every((height) => Math.abs(height - chapterHeights[0]) < 1), 'Trois chapitres de hauteur strictement égale à 1440 px')
  await desktop.locator('.header-cta').click()
  await desktop.locator('input[name="universe"][value="suites"]').check()
  await desktop.locator('input[name="name"]').fill('Camille Dupont')
  await desktop.locator('input[name="email"]').fill('camille@example.fr')
  await desktop.locator('input[name="arrival"]').fill('2027-05-22')
  await desktop.locator('input[name="departure"]').fill('2027-05-24')
  await desktop.locator('textarea[name="message"]').fill('Une parenthèse en amoureux dans la suite Eau.')
  await desktop.locator('input[name="consent"]').check()
  await desktop.getByRole('button', { name: 'Préparer ma demande', exact: true }).click()
  await desktop.locator('#draft-heading').waitFor()
  assert((await desktop.locator('.draft-preview').innerText()).includes('Camille Dupont'), 'Demande personnalisée générée')
  assert((await desktop.getByRole('link', { name: 'Envoyer par e-mail' }).getAttribute('href')).includes('contact@chateaulatoursegur.com'), 'Transmission réelle par messagerie')
  await desktop.screenshot({ path: 'artifacts/desktop-inquiry.png' })
  const modalScan = await new AxeBuilder({ page: desktop }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
  console.log('MODAL ACCESSIBILITY', JSON.stringify(modalScan.violations.map((violation) => ({ id: violation.id, impact: violation.impact, description: violation.description, nodes: violation.nodes.map((node) => ({ target: node.target, summary: node.failureSummary })) })), null, 2))
  assert(modalScan.violations.length === 0, 'Confirmation sans erreur d’accessibilité détectée')
  await desktop.getByRole('button', { name: 'Copier ma demande', exact: true }).click()
  assert((await desktop.evaluate(() => navigator.clipboard.readText())).includes('Camille Dupont'), 'Copie de la demande dans le presse-papiers')
  await desktop.getByRole('button', { name: 'Modifier ma demande' }).click()
  assert(await desktop.locator('input[name="name"]').inputValue() === 'Camille Dupont', 'Coordonnées conservées lors de la modification')
  assert(await desktop.locator('textarea[name="message"]').inputValue() === 'Une parenthèse en amoureux dans la suite Eau.', 'Message conservé lors de la modification')
  const formScan = await new AxeBuilder({ page: desktop }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
  console.log('FORM ACCESSIBILITY', JSON.stringify(formScan.violations.map((violation) => ({ id: violation.id, nodes: violation.nodes.map((node) => node.failureSummary) })), null, 2))
  assert(formScan.violations.length === 0, 'Formulaire sans erreur d’accessibilité détectée')
  await desktop.keyboard.press('Escape')
  assert(await desktop.locator('dialog').count() === 0, 'Fermeture accessible par Échap')
  await desktop.locator('#spa .text-link').click()
  assert(await desktop.locator('dialog details').count() === 3, 'Trois expériences détaillées pour le spa')
  await desktop.locator('dialog summary').nth(1).click()
  assert(await desktop.locator('dialog details').nth(1).getAttribute('open') !== null, 'Accordéons fonctionnels')
  await desktop.keyboard.press('Escape')
  await desktop.locator('#galerie').scrollIntoViewIfNeeded()
  await desktop.locator('.gallery-filters').getByRole('button', { name: 'Le spa', exact: true }).click()
  await desktop.waitForTimeout(650)
  assert(await desktop.locator('.gallery-photo').count() === 2, 'Filtrage de la galerie')
  await desktop.locator('.gallery-photo').first().click()
  const initialCaption = await desktop.locator('.lightbox-bottom p').innerText()
  await desktop.getByRole('button', { name: 'Photographie suivante' }).click()
  assert(await desktop.locator('.lightbox-bottom p').innerText() !== initialCaption, 'Navigation de la visionneuse')
  await desktop.keyboard.press('ArrowLeft')
  assert(await desktop.locator('.lightbox-bottom p').innerText() === initialCaption, 'Navigation clavier de la visionneuse')
  await desktop.keyboard.press('Escape')
  await desktop.locator('.gallery-filters').getByRole('button', { name: 'Tous les instants' }).click()
  await desktop.waitForTimeout(600)
  for (let top = 0; top < await desktop.evaluate(() => document.body.scrollHeight); top += 650) {
    await desktop.evaluate((y) => window.scrollTo(0, y), top)
    await desktop.waitForTimeout(120)
  }
  await desktop.waitForTimeout(1000)
  await desktop.screenshot({ path: 'artifacts/desktop-full.png', fullPage: true })
  const scan = await new AxeBuilder({ page: desktop }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
  console.log('DESKTOP ACCESSIBILITY', JSON.stringify(scan.violations.map((violation) => ({ id: violation.id, impact: violation.impact, description: violation.description, nodes: violation.nodes.map((node) => ({ target: node.target, summary: node.failureSummary })) })), null, 2))
  assert(scan.violations.length === 0, 'Page ordinateur sans erreur d’accessibilité détectée')
  assert(await desktop.locator('img').evaluateAll((images) => images.every((image) => image.complete && image.naturalWidth > 0)), 'Toutes les photographies sont chargées')
  await desktop.getByRole('button', { name: 'Mentions légales', exact: true }).click()
  assert(await desktop.locator('.legal-content').count() === 1, 'Mentions légales accessibles')
  await desktop.keyboard.press('Escape')

  const mobileContext = await browser.newContext({ viewport: { width: 375, height: 812 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true })
  const mobile = await mobileContext.newPage()
  mobile.on('pageerror', (error) => errors.push(error.message))
  await mobile.goto('http://127.0.0.1:4179/', { waitUntil: 'networkidle' })
  await mobile.waitForTimeout(1500)
  await mobile.screenshot({ path: 'artifacts/mobile-hero.png' })
  assert(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Aucun débordement à 375 px')
  await mobile.getByRole('button', { name: 'Ouvrir le menu' }).click()
  await mobile.waitForTimeout(500)
  await mobile.screenshot({ path: 'artifacts/mobile-menu.png' })
  const menuScan = await new AxeBuilder({ page: mobile }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
  console.log('MENU ACCESSIBILITY', JSON.stringify(menuScan.violations.map((violation) => ({ id: violation.id, nodes: violation.nodes.map((node) => ({ target: node.target, summary: node.failureSummary })) })), null, 2))
  assert(menuScan.violations.length === 0, 'Menu mobile accessible')
  await mobile.locator('.mobile-menu nav').getByRole('button', { name: 'Séminaires & événements' }).click()
  await mobile.waitForTimeout(1500)
  assert(await mobile.locator('dialog').count() === 0, 'Navigation mobile fonctionnelle')
  await mobile.locator('#evenements .text-link').click()
  await mobile.getByRole('button', { name: 'Parlons de vos envies' }).click()
  assert(await mobile.locator('input[value="evenements"]').isChecked(), 'Demande contextualisée pour les événements')
  await mobile.waitForTimeout(500)
  assert(await mobile.locator('dialog').evaluate((dialog) => dialog.scrollTop) < 10, 'Formulaire mobile ouvert en haut de la fenêtre')
  assert(await mobile.locator('dialog').evaluate((dialog) => dialog.scrollWidth <= dialog.clientWidth), 'Formulaire sans débordement mobile')
  await mobile.screenshot({ path: 'artifacts/mobile-booking.png' })
  const mobileFormScan = await new AxeBuilder({ page: mobile }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
  console.log('MOBILE FORM ACCESSIBILITY', JSON.stringify(mobileFormScan.violations.map((violation) => ({ id: violation.id, nodes: violation.nodes.map((node) => node.failureSummary) })), null, 2))
  assert(mobileFormScan.violations.length === 0, 'Formulaire mobile accessible')
  await mobile.getByRole('button', { name: 'Fermer la fenêtre' }).click()
  for (let top = 0; top < await mobile.evaluate(() => document.body.scrollHeight); top += 600) {
    await mobile.evaluate((y) => window.scrollTo(0, y), top)
    await mobile.waitForTimeout(100)
  }
  await mobile.waitForTimeout(1000)
  await mobile.screenshot({ path: 'artifacts/mobile-full.png', fullPage: true })
  assert(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Page complète sans débordement mobile')
  const mobileScan = await new AxeBuilder({ page: mobile }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
  console.log('MOBILE ACCESSIBILITY', JSON.stringify(mobileScan.violations.map((violation) => ({ id: violation.id, impact: violation.impact, nodes: violation.nodes.map((node) => ({ target: node.target, summary: node.failureSummary })) })), null, 2))
  assert(mobileScan.violations.length === 0, 'Page mobile sans erreur d’accessibilité détectée')
  for (const width of [320, 768, 1024]) {
    await mobile.setViewportSize({ width, height: 900 })
    await mobile.waitForTimeout(500)
    assert(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Aucun débordement à ${width} px`)
  }
  const reducedContext = await browser.newContext({ viewport: { width: 375, height: 812 }, reducedMotion: 'reduce' })
  const reduced = await reducedContext.newPage()
  await reduced.goto('http://127.0.0.1:4179/', { waitUntil: 'networkidle' })
  assert(await reduced.locator('.hero-image img').evaluate((image) => getComputedStyle(image).animationName) === 'none', 'Préférence de mouvement réduit respectée')
  assert(errors.length === 0, `Aucune erreur JavaScript : ${errors.join('; ') || 'OK'}`)
  console.log('CHECKS PASSED', results.length, results)
} finally {
  await browser.close()
  server.close()
}
